### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by rcemper** [SeanConnelly/Kozo#1]
ERROR! Directory '/opt/irisbuild/src/kozo' does not exist.
ERROR: Service 'iris' failed to build : 
The command '/bin/sh -c iris start IRIS
     && iris session IRIS < iris.script     && iris stop IRIS quietly' 
     returned a non-zero   code: 1
     
 There is only subdirectory /src/csp/  but no /src/kozo/

**Comment by SeanConnelly** [comment]
Should be fixed now.

**Comment by rcemper** [comment]
Thanks it's fixed!
