### ISSUE TITLE
Class Climate.TemperatureByCity is missing

### ISSUE THREAD

**Issue by rcemper** [SeanConnelly/Kozo#4]
For Demo the README says

do ##class(**Climate.TemperatureByCity)**.ImportFromGitHub("location of the data folder here")

Where is this class ?
actually not included in Repo nor ZPM

**Comment by SeanConnelly** [comment]
Should be pushed everywhere now

**Comment by rcemper** [comment]
its in repo , not in module.xml yet  
see next issue
