### ISSUE TITLE
Demo Links for Docker require adjustment

### ISSUE THREAD

**Issue by rcemper** [SeanConnelly/Kozo#6]
- It looks like the Community Version causes a collision with the 5 Connections limit
in a normal installation 
Kitchen Sink: [http://localhost:42773/kozo/Kozo.Editor.cls?ns=USER&doc=Kozo.Samples.KitchenSink.cls](http://localhost:42773/kozo/Kozo.Editor.cls?doc=Kozo.Samples.KitchenSink.cls)

- Exploring Temperature Data Part 1: [http://localhost:42773/kozo/Kozo.Editor.cls?ns=USER&doc=Kozo.Samples.ExploringTemperatureData.cls](http://localhost:42773/kozo/Kozo.Editor.cls?doc=Kozo.Samples.ExploringTemperatureData.cls)

- Exploring Temperature Data Part 2: [http://localhost:42773/kozo/Kozo.Editor.cls?ns=USER&doc=Kozo.Samples.ExploringTemperatureDataPart2.cls](http://localhost:42773/kozo/Kozo.Editor.cls?doc=Kozo.Samples.ExploringTemperatureDataPart2.cls)
 
Works fine but with docker, they don't move. BUT this adjustment works perfect as expected:
-  Kitchen Sink:      http://localhost:42773/kozo/Kozo.Samples.KitchenSink.cls
-  Exploring Temperature Data Part 1:      http://localhost:42773/kozo/Kozo.Samples.ExploringTemperatureData.cls
-  Exploring Temperature Data Part 2:     http://localhost:42773/kozo/Kozo.Samples.ExploringTemperatureDataPart2.cls

Warning: Service Unavailable or no response indicated that you collided
with the crazy 5 connections limit of community license in combination with CSP Gace Period:
You need to cancel WebSessions manually from SMP !

Pls. adjust in README

**Comment by SeanConnelly** [comment]
Done. The first set of links were added as a pull request in the first place. I really need to spend some time with docker over the weekend and understand the dependancies a little more. It's just been one thing too many this week to test in depth.
Tbh, these links wont be needed as I will also add a management page tomorrow.

**Comment by rcemper** [comment]
thanks
